add SelectKBest using chi-squared
opentutor/opentutor-classifier pull request #88
Opened 2021-06-15 17:33 UTC by adityajn105

1. Added SelectKbest feature selection method using the chi-squared test.
2. K set to 10 each for good and bad features
3. Added a test to verify the parameter selection using SelectKBest.
4. Moved some preprocessing and feature generation code from expectations.py to features.py

2021-06-16 21:47 UTC, beatthat approved these changes
looks great!

2021-06-16 21:48 UTC, beatthat requested changes
looks great! There is some conflict with main (lots of people working same repo)

Can you resolve the conflict and then just make a release (e.g. 2.4.0-alpha.$NEXT)

I can smoke test the release locally, and if looks good, I will merge

2021-06-16 23:18 UTC, adityajn105 commented
1. I resolved merge conflicts with the main branch
2. I also made a release 2.4.0-alpha.3 using this branch.

2021-06-18 19:49 UTC, beatthat commented
> 1. I resolved merge conflicts with the main branch
> 2. I also made a release 2.4.0-alpha.3 using this branch.

i still see the merge conflicts...does that display differently for you?

2021-06-18 20:13 UTC, adityajn105 commented
Merge conflicts are resolved.

2021-06-18 20:30 UTC, beatthat reviewed
see inline

2021-06-18 20:30 UTC, beatthat commented on sentence-transformer/bert-base-nli-mean-tokens/similarity_evaluation_results.csv
> +epoch,steps,cosine_pearson,cosine_spearman,euclidean_pearson,euclidean_spearman,manhattan_pearson,manhattan_spearman
does this file belong in this branch / PR?

2021-06-18 20:36 UTC, beatthat approved these changes
looks good!

2021-06-18 20:36 UTC, merged